# Generated by Django 6.0.5 on 2026-05-14 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_chatmessage_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='conversation',
            name='mode',
            field=models.CharField(default='coding', max_length=50),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='ai_response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation'),
        ),
    ]
