# Generated by Django 6.0.5 on 2026-05-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('document', 'Document'), ('image', 'Image')], default='document', max_length=20),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='filename',
            field=models.CharField(default='default_file', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
